services:
  app:
    image: sa2avroo/test-react:latest
    # ports:
    #   - "3000:3000"

  api:
    image: sa2avroo/test-node:latest
    # ports:
    #   - "5000:5000"

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:alpine
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - api
      - app
        
  certbot:
    image: sa2avroo/certbot:latest
    container_name: certbot
    volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=sa2avroo@gmail.com
      - CERTBOT_DOMAINS=apii.fr.to,npm.fr.to,www.avro.fr.to
      # - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      # - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do /usr/local/bin/manage-certificates.sh; sleep 24h; done;'"

