name: Build and Push Docker image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build and push Docker image react client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: sa2avroo/test-react:latest

      - name: Build and push Docker image nodejs server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: sa2avroo/test-node:latest

      - name: Build and push Docker image certbot
        uses: docker/build-push-action@v4
        with:
          context: ./certbot
          push: true
          tags: sa2avroo/certbot:latest